/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"header.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	volatile uint32_t *pGPIOA_clkEn_reg=(uint32_t*)(RCC_BASE_ADDR+0x30);
	*pGPIOA_clkEn_reg|=(1<<0); //port A clock enable

	volatile uint32_t *pGPIOA_mode_reg=(uint32_t*)(GPIOA_BASE_ADDR+0x0);
	*pGPIOA_mode_reg|=(2<<16); //PA8 alternate function mode

	volatile uint32_t *pGPIOA_altFun_reg=(uint32_t*)(GPIOA_BASE_ADDR+0x24);
	*pGPIOA_altFun_reg&=~(0xF<<0); //Alternate function 0 selected for PA8

	volatile uint32_t *pRCC_CFGR=(uint32_t*)(RCC_BASE_ADDR+0x08);
	*pRCC_CFGR&=~(3<<21); //MCO1 HSI clock selected
//	volatile uint32_t *pRCC_CFGR=(uint32_t*)(RCC_BASE_ADDR+0x08);
//	*pRCC_CFGR&=~(3<<21); //MCO1 HSE clock selected
//	*pRCC_CFGR|=(2<<21);

	volatile uint32_t *pRCC_CR=(uint32_t*)(RCC_BASE_ADDR);
	*pRCC_CR|=(1<<0); //HSI clock enable
    /* Loop forever */
	for(;;);
}
