/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include<stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//PA8 as clock output

	printf("Welcome back\n");
	const uint32_t GPIOA_base_addr=0x40020000;
	const uint32_t RCC_base_addr=0x40023800;
	volatile uint32_t *const GIOA_mode=(uint32_t*)GPIOA_base_addr;
	volatile uint32_t *const GIOA_altFun=(uint32_t*)(GPIOA_base_addr+0x24);
	volatile uint32_t *const RCC_AHB1ENR=(uint32_t*)(RCC_base_addr+0x30);
	volatile uint32_t *const RCC_CFGR=(uint32_t*)(RCC_base_addr+0x08);

	//GPIOA peripheral clock enable
	*RCC_AHB1ENR|=(1<<0);

	//GPIOA mode altfun set
	*GIOA_mode&=~(3<<16); //clear 16,17th bit
	*GIOA_mode|=(2<<16); //set 10

	//GPIOA altfun0 set for PA8
	*GIOA_altFun&=~(0xf<<0);

	//PA8 MCO1 prescaler 100(Div2) set
	*RCC_CFGR&=~(7<<24);
	*RCC_CFGR|=(4<<24);


	/* Loop forever */
	for(;;);
}
